### ISSUE TITLE
How is this organization & package related to Vite's import.meta.env?

### ISSUE THREAD

**Issue by Xarvalus** [runtime-env/import-meta-env#1167]
Hi Ernest,
First thank you for your effort & dedication for this project - I'm using it for containerizing our frontend and it works great 🙂

According to [https://vitejs.dev/guide/env-and-mode.html](https://vitejs.dev/guide/env-and-mode.html):

> Vite exposes env variables on the special import.meta.env object.

But I don't see this package being imported in Vite's [package.json](https://github.com/vitejs/vite/blob/main/package.json)

How is this related? Does they really use your package or just the naming is confusing us to think they does?

**Comment by iendeavor** [comment]
Hello,

Thank you for using our project to containerize your frontend. I'm delighted to hear it's working well for you.

Regarding your question about Vite and the import-meta-env packages, it's important to clarify that the import-meta-env packages are designed to offer a framework-agnostic solution for developers working with JavaScript. They are not directly related to Vite and are not included in Vite's package.json.

Additionally, it's worth noting that import-meta-env supports various libraries and plugins like Babel, SWC, Webpack, Rollup, or RSPack, providing flexibility and compatibility with a range of tools.

I hope this explanation provides the clarity you were seeking. If you have any further questions or require additional information, please feel free to ask.

**Comment by Xarvalus** [comment]
Thanks for clarifying! I would suggest to maybe rename the **import.meta.env** variable or write the disclaimer that your project is not related to Vite. I just find the usage of the same variable as in Vite being misleading & making an impression of being Vite-related implementation

Cheers
