### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'edgesOut') when installing unplugin

### ISSUE THREAD

**Issue by amasukakarot** [runtime-env/import-meta-env#1182]
Command: npm i -D @import-meta-env/unplugin --verbose

Error logs:
npm verb stack TypeError: Cannot read properties of null (reading 'edgesOut')
npm verb stack     at #loadPeerSet (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1302:38)
npm verb stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm verb stack     at async #buildDepStep (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:917:11)
npm verb stack     at async Arborist.buildIdealTree (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:196:7)
npm verb stack     at async Promise.all (index 1)
npm verb stack     at async Arborist.reify (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
npm verb stack     at async Install.exec (/opt/homebrew/lib/node_modules/npm/lib/commands/install.js:149:5)
npm verb stack     at async module.exports (/opt/homebrew/lib/node_modules/npm/lib/cli-entry.js:61:5)
npm verb cwd /Users/ujaved/consumer/finance-application-ui
npm verb Darwin 22.6.0
npm verb node v20.5.1
npm verb npm  v9.8.0
npm ERR! Cannot read properties of null (reading 'edgesOut')
npm verb exit 1
npm verb unfinished npm timer reify 1698774328334
npm verb unfinished npm timer reify:loadTrees 1698774328337
npm verb unfinished npm timer idealTree:buildDeps 1698774328807
npm verb unfinished npm timer idealTree:#root 1698774328808
npm verb code 1

It looks like it has an issue with Arborist, but I wasn't too sure.

I'm able to run this successfully: npm i @import-meta-env/unplugin@0.4.10

**Comment by mhemmings** [comment]
@iendeavor I can confirm that it's impossible to install `@import-meta-env/unplugin` from NPM. Maybe related to #1190

**Comment by iendeavor** [comment]
Please try this for now:

```sh
npm install @import-meta-env/unplugin@^0.5.1 --save-dev
```
or: 

```sh
npm install @import-meta-env/unplugin@latest --save-dev
```

**Comment by mhemmings** [comment]
That now works, but installing `@import-meta-env/cli` fails 
```
code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @import-meta-env/cli@0.6.7
npm ERR! Found: @import-meta-env/unplugin@0.5.1
npm ERR! node_modules/@import-meta-env/unplugin
npm ERR!   dev @import-meta-env/unplugin@"^0.5.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional @import-meta-env/unplugin@"^0.4.8" from @import-meta-env/cli@0.6.7
npm ERR! node_modules/@import-meta-env/cli
npm ERR!   dev @import-meta-env/cli@"v0.6.7" from the root project
npm ERR!   peerOptional @import-meta-env/cli@"^0.5.1 || ^0.6.0" from @import-meta-env/unplugin@0.5.1
npm ERR!   node_modules/@import-meta-env/unplugin
npm ERR!     dev @import-meta-env/unplugin@"^0.5.1" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @import-meta-env/unplugin@0.4.10
npm ERR! node_modules/@import-meta-env/unplugin
npm ERR!   peerOptional @import-meta-env/unplugin@"^0.4.8" from @import-meta-env/cli@0.6.7
npm ERR!   node_modules/@import-meta-env/cli
npm ERR!     dev @import-meta-env/cli@"v0.6.7" from the root project
npm ERR!     peerOptional @import-meta-env/cli@"^0.5.1 || ^0.6.0" from @import-meta-env/unplugin@0.5.1
npm ERR!     node_modules/@import-meta-env/unplugin
npm ERR!       dev @import-meta-env/unplugin@"^0.5.1" from the root project
```

**Comment by mhemmings** [comment]
Thanks @iendeavor, I think your CI workflow is failing though!

**Comment by mhemmings** [comment]
Looks like everything is working again. Thanks!
