### ISSUE TITLE
Security Issue while using in production

### ISSUE THREAD

**Issue by Scientist786** [runtime-env/import-meta-env#1203]
Hello,
I recently came across your tool while I was searching for Build Once Deploy Many. I was searching for a way to overwrite environment variables after my react build was compiled successfully. I was using Github Actions to build and deploy my app. I actually didn't want to push my env file in Git and didn't want to use secrets because of some reasons. This was the perfect solution for me and I used the "npx import-meta-env -x .env -p build/index.html" command to successfully replace my env variables but the issue is when I open my website and go to Page Source, I can see my secret keys inside the Page Source. Is there any way to protect that or the library is supposed to be used this way?

**Comment by iendeavor** [comment]
You need to run:
`npx import-meta-env -x .env.example -p build/index.html`
instead of:
`npx import-meta-env -x .env -p build/index.html`

`-x` is used for define the environment keys you want to use in client side.

**Comment by Deploy-CICD** [comment]
Thanks alot iendeavor for your quick reply. When I set the variable in .env.example and run the command
``npx import-meta-env -x .env.example -p build/index.html``
It gives me following error
``
[import-meta-env]: Some environment variables are not defined.

The following variables were defined in .env.example file but are not defined in the environment:

```
HELLO=123
```

Here's what you can do:
- Set them to environment variables on your system.
- Add them to .env file.
- Remove them from .env.example file.

/<my_path>/create-react-app-example/node_modules/@import-meta-env/cli/bin/import-meta-env.js:3383
    throw ReferenceError(`Some environment variables are not defined.`);
    ^

ReferenceError: Some environment variables are not defined.
    at Object.resolveEnv (<my_path>/create-react-app-example/node_modules/@import-meta-env/cli/bin/import-meta-env.js:3383:11)
    at main (<my_path>/create-react-app-example/node_modules/@import-meta-env/cli/bin/import-meta-env.js:9658:18)
    at Object.<anonymous> (<my_path>/create-react-app-example/node_modules/@import-meta-env/cli/bin/import-meta-env.js:9703:3)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
``
When I export Hello as an environment variable on my system, it works without any errors but when I serve the build via nginx and open localhost, I can still see the value of HELLO in my page source

**Comment by iendeavor** [comment]
Closing for now. Feel free to reopen if you still have questions :）
