### ISSUE TITLE
Runtime Error: `Object prototype may only be an Object or null: import_meta_env_placeholder` using new variables in .env file.

### ISSUE THREAD

**Issue by bayu01** [runtime-env/import-meta-env#1252]
Description:
Using new variables in an `.env` file that are not present in `env.example.public` blows up with error.

Steps to reproduce:
1. Start from https://github.com/runtime-env/import-meta-env/tree/main/packages/examples/create-react-app-example
2. update `webpack.config.js` with:
```
    plugins: [
      require("@import-meta-env/unplugin").webpack({
        env: ".env",
        example: ".env.example.public",
      }),
```
3. update `package.json` to just read env vars from file:
```
    "dev": "node scripts/start.js",
```

4. Add an `.env`  file with more env vars than the ones listed in env.example.public and attempt to use them in `App.js`

```env
# .env
HELLO=import-meta-env
MORE_ENV_VARS=Something new
```

```javascript
// App.js
import React from 'react';
function App() {
  console.log(import.meta.env.MORE_ENV_VARS);
  return <h1>Hello: {import.meta.env.HELLO}</h1>;
}
export default App;
```

---

Additional Information:

Usage of import-meta-env: Planning to use it to inject a LOT of env vars via our convoluted deployment process in which we create EC2s via IaC (terraform). The EC2 startup script creates an .env file which we'll attempt to read and use the import-meta-env to rewrite the public.html and host it on an nginx container.

JavaScript Bundler/Transformer: ejected `create-react-app` application similar to [example/create-react-app-example](https://github.com/runtime-env/import-meta-env/tree/main/packages/examples/create-react-app-example)

Node.js Version: [Node 20.11.1]
import-meta-env Version: [    
    "@import-meta-env/babel": "^0.4.5",
    "@import-meta-env/cli": "^0.6.8",
    "@import-meta-env/unplugin": "^0.5.1"
]

**Comment by bayu01** [comment]
What is worse, once this happens its hard to correct the mistake. 
Adding any new env vars from `.env` to `env.example.public` and deleting the node_modules/.cache multiple times can fix the mistake.

**Comment by soc221b** [comment]
For security reason, this package will ONLY [statically replace](https://import-meta-env.org/guide/getting-started/introduction.html#compile-time-transform-modes) those environment variables listed in the example file.

You could integrate with the [@import-meta-env/typescript](https://import-meta-env.org/guide/tools/typescript.html) plugin to catch such error in compile-time.
