### ISSUE TITLE
Kubernetes secrets

### ISSUE THREAD

**Issue by tomcoquery** [runtime-env/import-meta-env#1571]
I believe I am having a similar issue as [this discussion](https://github.com/runtime-env/import-meta-env/discussions/1023)

This is my setup :

- React + Vite;
- Docker;
- Kubernetes;

So my application is using secrets from Kubernetes and passes them as arguments to Docker using the [secret flag](https://docs.docker.com/build/building/secrets/). 

That's where my issue is, my env variables are not defined and therefore cannot be accessed by import-meta-env.

Any help would be much appreciated

**Comment by soc221b** [comment]
You should NEVER expose *secrets* to clients.

**Comment by tomcoquery** [comment]
Hey sorry, i wasnt clear, my env doesnt contain secrets but anyway, i managed to solve the issue. 

I had an issue with your [docker example](https://github.com/runtime-env/import-meta-env/blob/main/packages/examples/docker-starter-example/Dockerfile), the bash script was throwing an error saying it couldn't find import-meta-env-alpine even though it was present. 

I managed to make it work with your docker-compose example>

Thanks for the tool, it's great !
